/* GENERATED by scripts/gen-foods.js. Do not edit by hand. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else { root.CAG = root.CAG || {}; root.CAG.FOODS = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  /* e emoji, n name, r radius, c colour, rest bounce, fric grip, dens weight, tilt lean when dropped (radians),
     poly outline (non-round foods), ext farthest point, hw half width, es/ey emoji size and offset,
     art half side of the food's own picture (web/img/foods/<level>.webp) and, for each face
     (open, half closed, closed, surprised), which picture of the row it uses */
  return [
 {
  "e": "🍬",
  "n": "Candy",
  "r": 14,
  "c": "#ff8fb1",
  "rest": 0.55,
  "fric": 0.2,
  "dens": 0.0008,
  "ext": 14,
  "hw": 14,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 14.187,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍪",
  "n": "Cookie",
  "r": 19,
  "c": "#e3ad72",
  "rest": 0.15,
  "fric": 0.6,
  "dens": 0.001,
  "ext": 19,
  "hw": 19,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 19.7,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍙",
  "n": "Onigiri",
  "r": 25,
  "c": "#fdfdfd",
  "rest": 0.08,
  "fric": 0.7,
  "dens": 0.0012,
  "shape": "tri",
  "ext": 31.318,
  "hw": 27.298,
  "es": 1.05,
  "ey": 0.1,
  "art": {
   "half": 31.155,
   "faces": [
    0,
    1,
    2,
    3
   ]},
  "poly": [
   {"x": -1.747, "y": -31.269},
   {"x": 1.884, "y": -30.934},
   {"x": 8.251, "y": -27.136},
   {"x": 18.082, "y": -14.457},
   {"x": 24.17, "y": -3.956},
   {"x": 27.298, "y": 10.455},
   {"x": 25.567, "y": 17.94},
   {"x": 17.021, "y": 22.799},
   {"x": 1.996, "y": 23.748},
   {"x": -12.136, "y": 22.911},
   {"x": -18.503, "y": 21.626},
   {"x": -24.201, "y": 18.163},
   {"x": -26.882, "y": 10.79},
   {"x": -23.474, "y": -6.023},
   {"x": -16.604, "y": -18.59},
   {"x": -10.74, "y": -26.633}
  ]},
 {
  "e": "🍩",
  "n": "Donut",
  "r": 31,
  "c": "#c9a2f5",
  "rest": 0.38,
  "fric": 0.06,
  "dens": 0.0009,
  "ext": 31,
  "hw": 31,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 31.434,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🥤",
  "n": "CAG Energy",
  "r": 38,
  "c": "#3bc7f5",
  "rest": 0,
  "fric": 0.3,
  "dens": 0.001,
  "shape": "pill",
  "tilt": 0.25,
  "ext": 52.253,
  "hw": 51.527,
  "es": 1.1,
  "ey": 0.07,
  "art": {
   "half": 51.614,
   "faces": [
    0,
    0,
    0,
    0
   ]},
  "poly": [
   {"x": -39.153, "y": -23.412},
   {"x": -33.035, "y": -23.893},
   {"x": 41.555, "y": -24.168},
   {"x": 43.892, "y": -23.481},
   {"x": 48.567, "y": -18.531},
   {"x": 50.011, "y": -12.55},
   {"x": 50.629, "y": -3.819},
   {"x": 49.873, "y": 12.955},
   {"x": 48.086, "y": 19.417},
   {"x": 41.83, "y": 24.023},
   {"x": -36.884, "y": 24.092},
   {"x": -48.502, "y": 19.211},
   {"x": -50.152, "y": 14.33},
   {"x": -51.527, "y": 0.787},
   {"x": -50.84, "y": -12.069},
   {"x": -47.54, "y": -19.63}
  ]},
 {
  "e": "🧇",
  "n": "Waffle",
  "r": 46,
  "c": "#f5b942",
  "rest": 0.08,
  "fric": 0.4,
  "dens": 0.0018,
  "ext": 46,
  "hw": 46,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 48.747,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍜",
  "n": "Ramen",
  "r": 55,
  "c": "#74dcc9",
  "rest": 0.3,
  "fric": 0.4,
  "dens": 0.001,
  "ext": 55,
  "hw": 55,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 55.789,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍕",
  "n": "Pizza",
  "r": 64,
  "c": "#ff7566",
  "rest": 0.2,
  "fric": 0.12,
  "dens": 0.001,
  "ext": 64,
  "hw": 64,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 65.541,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍣",
  "n": "Sushi",
  "r": 74,
  "c": "#ff9d6c",
  "rest": 0.08,
  "fric": 0.5,
  "dens": 0.0018,
  "ext": 74,
  "hw": 74,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 75.779,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🎂",
  "n": "Cake",
  "r": 85,
  "c": "#8fd0ff",
  "rest": 0.25,
  "fric": 0.4,
  "dens": 0.0009,
  "ext": 85,
  "hw": 85,
  "es": 1.18,
  "ey": 0.07,
  "art": {
   "half": 86.909,
   "faces": [
    0,
    0,
    0,
    0
   ]}},
 {
  "e": "🍱",
  "n": "Big Order",
  "r": 97,
  "c": "#ff5a4a",
  "rest": 0.08,
  "fric": 0.5,
  "dens": 0.002,
  "shape": "box",
  "ext": 113.688,
  "hw": 86.223,
  "es": 1.25,
  "ey": 0.07,
  "art": {
   "half": 88.824,
   "faces": [
    0,
    0,
    0,
    0
   ]},
  "poly": [
   {"x": -75.02, "y": -82.886},
   {"x": -46.714, "y": -87.881},
   {"x": 47.44, "y": -87.881},
   {"x": 75.143, "y": -82.886},
   {"x": 84.074, "y": -75.467},
   {"x": 86.192, "y": -7.197},
   {"x": 86.192, "y": 10.815},
   {"x": 84.225, "y": 76.361},
   {"x": 75.294, "y": 85.141},
   {"x": 5.813, "y": 88.018},
   {"x": -2.058, "y": 88.168},
   {"x": -75.173, "y": 85.141},
   {"x": -84.256, "y": 76.21},
   {"x": -86.223, "y": 10.514},
   {"x": -86.223, "y": -6.743},
   {"x": -84.103, "y": -75.317}
  ]}
];
});
