/*
 * Wraps the pinned Matter.js build so that every `Math` reference inside it
 * resolves to our deterministic Math (shared/detmath.js).
 * Run: node scripts/build-matter.js   (only needed if the vendored file changes)
 */
const fs = require('fs');
const path = require('path');
const src = fs.readFileSync(path.join(__dirname, '..', 'vendor', 'matter-0.19.0.min.js'), 'utf8');
const out = `/* GENERATED by scripts/build-matter.js from vendor/matter-0.19.0.min.js (MIT, see vendor/matter-LICENSE.txt). Do not edit. */
(function (root, wrap) {
  var isNode = typeof module === 'object' && module.exports;
  var detMath = isNode ? require('./detmath.js') : root.CAG.detMath;
  var M = wrap(detMath);
  if (isNode) module.exports = M; else { root.CAG = root.CAG || {}; root.CAG.Matter = M; }
})(typeof self !== 'undefined' ? self : this, function (Math) {
  var module = { exports: {} }, exports = module.exports, define = undefined;
${src}
  return module.exports;
});
`;
fs.writeFileSync(path.join(__dirname, '..', 'shared', 'matter-det.js'), out);
console.log('shared/matter-det.js written,', out.length, 'bytes');
