/*
 * Generates shared/foods.js: the food table with the outline of the
 * non-round foods precomputed and rounded, so the game never has to build
 * them at runtime with non-deterministic math.
 * A food that has its own drawing (scripts/art.json, written by gen-art.py)
 * takes its outline from the drawing, at the same area as its plain shape,
 * so the food collides where it is drawn and stays the same size.
 * Run: node scripts/gen-foods.js   (only needed if a food or its drawing changes)
 */
const fs = require('fs');
const path = require('path');
const vm = require('vm');
// Plain Matter.js with the real Math: fine here, this is build time only.
const sandbox = { module: { exports: {} } }; sandbox.exports = sandbox.module.exports;
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '..', 'vendor', 'matter-0.19.0.min.js'), 'utf8'), sandbox);
const Vertices = sandbox.module.exports.Vertices;

const FOODS = [
  { e: '🍬', n: 'Candy',     r: 14, c: '#ff8fb1', rest: 0.55, fric: 0.20, dens: 0.0008 },
  { e: '🍪', n: 'Cookie',    r: 19, c: '#e3ad72', rest: 0.15, fric: 0.60, dens: 0.0010 },
  { e: '🍙', n: 'Onigiri',   r: 25, c: '#fdfdfd', rest: 0.08, fric: 0.70, dens: 0.0012, shape: 'tri' },
  { e: '🍩', n: 'Donut',     r: 31, c: '#c9a2f5', rest: 0.38, fric: 0.06, dens: 0.0009 },
  { e: '🥤', n: 'CAG Energy', r: 38, c: '#3bc7f5', rest: 0.00, fric: 0.30, dens: 0.0010, shape: 'pill', tilt: 0.25 },
  { e: '🍜', n: 'Ramen',     r: 46, c: '#74dcc9', rest: 0.08, fric: 0.40, dens: 0.0018 },
  { e: '🍔', n: 'Burger',    r: 55, c: '#a4d65e', rest: 0.30, fric: 0.40, dens: 0.0010 },
  { e: '🍕', n: 'Pizza',     r: 64, c: '#ff7566', rest: 0.20, fric: 0.12, dens: 0.0010 },
  { e: '🍛', n: 'Curry',     r: 74, c: '#f4b942', rest: 0.08, fric: 0.50, dens: 0.0018 },
  { e: '🎂', n: 'Cake',      r: 85, c: '#8fd0ff', rest: 0.25, fric: 0.40, dens: 0.0009 },
  { e: '🍱', n: 'Big Order', r: 97, c: '#ff5a4a', rest: 0.08, fric: 0.50, dens: 0.0020, shape: 'box' }
];
/* About the can: dropped flat, a long food lands dead, like a brick. Dropped leaning (tilt) it lands
   on a corner, hops and rocks before lying down. Its own bounce is 0 on purpose: with any bounce of
   its own that corner landing sends it cartwheeling across the jar. */
const r3 = (v) => Math.round(v * 1000) / 1000;
const artFile = path.join(__dirname, 'art.json');
const ART = fs.existsSync(artFile) ? JSON.parse(fs.readFileSync(artFile, 'utf8')) : {};

for (const f of FOODS) {
  const r = f.r; let pts = null, cr = 0;
  if (f.shape === 'tri') { const R = r * 1.5; pts = [{ x: 0, y: -R }, { x: R * 0.866, y: R * 0.5 }, { x: -R * 0.866, y: R * 0.5 }]; cr = r * 0.5; }
  if (f.shape === 'pill') { const w = r * 2.5, h = r * 1.5; pts = [{ x: -w / 2, y: -h / 2 }, { x: w / 2, y: -h / 2 }, { x: w / 2, y: h / 2 }, { x: -w / 2, y: h / 2 }]; cr = h * 0.49; }
  if (f.shape === 'box') { const s = r * 0.9; pts = [{ x: -s, y: -s }, { x: s, y: -s }, { x: s, y: s }, { x: -s, y: s }]; cr = r * 0.36; }
  f.ext = r; f.hw = r; f.es = 1.18; f.ey = 0.07;
  f.area = Math.PI * r * r;
  const art = ART[FOODS.indexOf(f)];
  // A round food keeps rolling as a circle: its drawing is sized to cover the same area as the circle
  // (the outline in art.json has area 1, and a circle of area 1 has radius 1 / sqrt(pi)).
  if (art && !pts) f.art = { half: r3(art.half * r * Math.sqrt(Math.PI)), faces: art.faces };
  if (!pts) continue;
  let poly = Vertices.chamfer(pts, cr, -1, 3, 14);
  f.area = Vertices.area(poly);
  if (art) {
    const k = Math.sqrt(f.area);
    poly = art.outline.map((p) => ({ x: p[0] * k, y: p[1] * k }));
    f.art = { half: r3(art.half * k), faces: art.faces };
  }
  const c = Vertices.centre(poly);
  f.poly = poly.map((p) => ({ x: r3(p.x - c.x), y: r3(p.y - c.y) }));
  f.ext = r3(Math.max(...f.poly.map((p) => Math.sqrt(p.x * p.x + p.y * p.y))));
  f.hw = r3(Math.max(...f.poly.map((p) => Math.abs(p.x))));
  if (f.shape === 'tri') { f.es = 1.05; f.ey = 0.1; }
  if (f.shape === 'pill') { f.es = 1.1; }
  if (f.shape === 'box') { f.es = 1.25; }
}

// node scripts/gen-foods.js --sizes: for gen-art.py, the radius of a circle with each food's area.
if (process.argv.includes('--sizes')) { console.log(JSON.stringify(FOODS.map((f) => Math.sqrt(f.area / Math.PI)))); process.exit(0); }
for (const f of FOODS) delete f.area;

const out = `/* GENERATED by scripts/gen-foods.js. Do not edit by hand. */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else { root.CAG = root.CAG || {}; root.CAG.FOODS = factory(); }
})(typeof self !== 'undefined' ? self : this, function () {
  'use strict';
  /* e emoji, n name, r radius, c colour, rest bounce, fric grip, dens weight, tilt lean when dropped (radians),
     poly outline (non-round foods), ext farthest point, hw half width, es/ey emoji size and offset,
     art half side of the food's own picture (web/img/foods/<level>.webp) and, for each face\n     (open, half closed, closed, surprised), which picture of the row it uses */
  return ${JSON.stringify(FOODS, null, 1).replace(/\n\s+("x"|"y")/g, ' $1').replace(/\{ "x"/g, '{"x"').replace(/\n\s+\}/g, '}')};
});
`;
fs.writeFileSync(path.join(__dirname, '..', 'shared', 'foods.js'), out);
console.log('shared/foods.js written;', FOODS.filter((f) => f.poly).map((f) => f.n + ':' + f.poly.length + ' points').join(', '));
