/* GENERATED by scripts/gen-cag.py. Do not edit by hand. Sizes and anchor points of the character. */
window.CAG_PUPPET = {
 "bodyWidth": 100,
 "handHeight": 30,
 "handTilt": 20,
 "outline": 1.05,
 "body": {
  "w": 560,
  "h": 509,
  "faces": 3,
  "roots": [
   [
    -0.3037,
    0.0409
   ],
   [
    0.2893,
    0.0409
   ]
  ],
  "base": 0.0,
  "skin": "#3cc4fb"
 },
 "hand": {
  "w": 300,
  "h": 280,
  "grip": [
   0.5867,
   0.5014
  ],
  "wrist": [
   0.0361,
   0.1737
  ],
  "away": [
   -0.9727,
   -0.2319
  ],
  "arm": 0.3247
 }
};
